### PR TITLE
Add a settings modal dialog

### PR DESCRIPTION
**Pull request by madx**
screenshot

### CODE REVIEW

**Comment by magsout** [comment]
:+1:

**Comment by kud** [comment]
You sure about shadows? I think I prefer flat design.

Plus, how it works for online version?

This should be stored in localStorage I think.

**Comment by madx** [comment]
ATM this is only a UI sketch, no settings management backend involved

As for the shadows, we already use a lot of them (on links for example), so we can't say we use flat design.

**Comment by kud** [comment]
Okay

**Pull request closed without merging**
