### PR TITLE
script to generate localhost alias + portrait support

### PR DESCRIPTION
**Pull request by MoOx**
I'm lazy.
Please review all commit one by one to make it faster to review.
- Contains scripts to generate images.js on a local folder + create a localhost alias for apache (eg: localhost/tab/)
- Allow you to get better portrait support

Example

screen shot 2014-12-30 at 12 32 29

This should not affect online version if you are a desktop user (assuming landscape).
If you are using portrait browser with landscape image, you will have now the same effect has landscape window + portrait image. Make sense to me.

This is supposed to be my last PR as vanilla code (in 3 index.js/css/html files).

Likely probable: future enhancement will be based on a huge refactoring with react.

### CODE REVIEW

**Comment by kud** [comment]
I'll review it when I'll time and also rebase it.

**Comment by MoOx** [comment]
Rebase (squash?) is not needed since every commit is standalone.

**Comment by kud** [comment]
Some mistakes in commit messages.

**Comment by MoOx** [comment]
Bump (call for review)

If nothing has been commented by the end of the week, I will assume it looks good & I will merge to continue to push stuff :shipit:

**Pull request merged**
