### PR TITLE
Add clock.

### PR DESCRIPTION
**Pull request by armandabric**
Simple proposal to add the time on the page.

### CODE REVIEW

**Comment by MoOx** [comment]
- Doesn't work on Firefox
- Said 16:0 for 16:00.
  Also according to #5 we would like to get it in top left, probably smaller, without the weird hover (maybe just the `color` as text shadow ?)

**Comment by armandabric** [comment]
Ho right! `appendText` seem to work differently on Firefox. I didn't know it. 

I've update the code.

**Comment by MoOx** [comment]
Nice thanks !

**Comment by kud** [comment]
I wanted it on the right :'(

**Comment by MoOx** [comment]
Well then 2 player on right, one on left, so change it... :)

**Comment by armandabric** [comment]
Right is nice.

hight five

**Pull request merged**
